---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - bioconda::star=2.7.11b
  - bioconda::samtools=1.20
  - conda-forge::gawk=5.1.0