---
# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/environment-schema.json
channels:
  - conda-forge
  - bioconda
dependencies:
  - conda-forge::biopython=1.86
  - conda-forge::r-optparse=1.7.1
  - conda-forge::r-upsetr=1.4.0
  - bioconda::bedtools=2.31.1
